# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: ContinuousIntegrationDemo

on:
  push:
    branches: [ "master" ]
    paths: ["12. Continuous Integration (CI)/01-Student-Registry-App/**"]
  pull_request:
    branches: [ "master" ]
    paths: ["12. Continuous Integration (CI)/01-Student-Registry-App/**"]

defaults:
  run:
    working-directory: ./12. Continuous Integration (CI)/01-Student-Registry-App/

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout all of the repo code 
      uses: actions/checkout@v3
      with:
        path: ./12. Continuous Integration (CI)/01-Student-Registry-App
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './12. Continuous Integration (CI)/01-Student-Registry-App/package-lock.json'
    - name: Install dependencies 
      run: npm ci
    - name: Build
      run: npm run build --if-present
    - name: Run tests
      run: npm test