name: ContinuousIntegrationDemo

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - name: Checkout all of the repo code 
      uses: actions/checkout@v3
      with:
        path: ./12. Continuous Integration (CI)/01-Student-Registry-App
        ref: ${{ github.ref }}
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies 
      run: npm ci
      working-directory: ./12. Continuous Integration (CI)/01-Student-Registry-App
    - name: Build
      run: npm run build --if-present
      working-directory: ./12. Continuous Integration (CI)/01-Student-Registry-App
    - name: Run tests
      run: npm test
      working-directory: ./12. Continuous Integration (CI)/01-Student-Registry-App
